-- liquibase formatted sql

-- changeset lafonina:1
CREATE TABLE dynamic_rules(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
product_name TEXT NOT NULL,
product_id TEXT NOT NULL,
product_text TEXT NOT NULL,
rule JSONB NOT NULL
);